name: GeoMesa
description: Website for GeoMesa

#url: "http://geomesa.org"
url: "http://localhost:4000"
repoUrl: "http://github.com/locationtech/geomesa"

paginate: 10

excerpt_separator: "<!--more-->"

markdown: kramdown
permalink: :title/
highlighter: pygments

authors:
    anthony: 
        display_name: Anthony Fox
    hunter:
        display_name: Hunter Provyn
    andrew:
        display_name: Andrew Hulbert
    chris:
        display_name: Chris Eichelberger
    cne1x:
        display_name: Chris Eichelberger
    emilio:
        display_name: Emilio Lahr-Vivaz
    aannex:
        display_name: Andrew Annex
    mikey:
        display_name: Michael Ronquest
    jake:
        display_name: Jake Kenneally
    andrew-and-jake:
        display_name: Andrew Annex and Jake Kenneally

gems:
  - jekyll-redirect-from

