name: GeoMesa
description: Website for GeoMesa

#url: "http://geomesa.org"
url: "http://localhost:4000"
repoUrl: "http://github.com/locationtech/geomesa"
stableVersion: "1.1.0-rc.6"
developmentVersion: "1.1.0-rc.7-SNAPSHOT"

paginate: 10

excerpt_separator: "<!--more-->"

markdown: kramdown
permalink: :title/
highlighter: pygments

authors:
    anthony: 
        display_name: Anthony Fox
    hunter:
        display_name: Hunter Provyn
    andrew:
        display_name: Andrew Hulbert
    chris:
        display_name: Chris Eichelberger
    cne1x:
        display_name: Chris Eichelberger
    emilio:
        display_name: Emilio Lahr-Vivaz
    aannex:
        display_name: Andrew Annex
    mikey:
        display_name: Michael Ronquest
    jake:
        display_name: Jake Kenneally
    atatusko:
        display_name: Alex Tatusko
    andrew-and-jake:
        display_name: Andrew Annex and Jake Kenneally
    chris-and-aannex:
        display_name: Chris Eichelberger and Andrew Annex
    the-trio:
        display_name: Chris Eichelberger, Andrew Annex, and Andrew Hulbert

gems:
  - jekyll-redirect-from

